### ISSUE TITLE
Addon not working on first load of youtube session in a tab

### ISSUE THREAD

**Issue by tgquan67** [mauricesvp/low-go#2]
According to my testing, the addon never works on youtube's first load in a tab. The behavior after that depends on where I start my youtube session:
- If I start from `youtube.com`or `https://www.youtube.com`, on initial load the addon doesn't work, but if I click on the youtube logo on the top left corner, it will start working.
- If I start from `https://www.youtube.com/feed/subscriptions` (which is my bookmark), no matter how many times I click on the youtube logo to navigate to youtube home, the addon won't work.

It seems it will work right away if I open a video by clicking on a youtube video URL and the video is opened in a new tab.

**Comment by mauricesvp** [comment]
Hi there,
as you correctly found out, I disable the Addon when initially loading a different page other than the start page, or a video page. I do this mainly as to avoid unnecessary load caused by the Extension. This is basically a trade-up which I decided in favor of the least possible performance penalty and not added convenience. Maybe I will change it if more people think it's better the other way.

**Comment by tgquan67** [comment]
Is it possible to have an option in addon settings page whether to keep the current behavior or load on any youtube subdomain/page? Or is it something unconfigurable once you have published the addon?

**Comment by Tsunayoshi** [comment]
+1 I always start youtube over my bookmark that leads to my subscriptions. I was already close to give it 1 star since it seems to not working.

**Comment by mauricesvp** [comment]
Thanks for the feedback folks, I added an Option to start the extension on any subdomain, and also enabled it by default. :)
